import SwiftUI
import KaiUI

/// The seam between iOS's static launch screen and the app.
///
/// A launch screen cannot animate, so it only shows the mark (`LaunchMark`) centred
/// on `LaunchBackground` — both generated by `scripts/generate_app_icon.swift`. This
/// overlay starts on that exact frame (the same mark, same height, centred on the
/// same full-screen colour), then gives it a sunrise: the sun dips behind the
/// horizon and springs back up, slightly past where it rests, and the mark zooms
/// away to reveal the app. It never takes touches; with Reduce Motion it only fades.
struct LaunchSplash: ViewModifier {
    /// Called once the overlay is gone (the root holds onboarding back until then).
    let onFinish: () -> Void

    /// Must match the launch mark's point height (`launchHeight` in the generator).
    private static let markHeight: CGFloat = 84

    private enum Phase { case resting, dip, rise, exit }

    @State private var phase: Phase = .resting
    @State private var finished = false
    @Environment(\.accessibilityReduceMotion) private var reduceMotion

    func body(content: Content) -> some View {
        content.overlay {
            if !finished {
                ZStack {
                    Color("LaunchBackground")
                    KaiMark(height: Self.markHeight, sunk: phase == .dip ? 150 : 0)
                        .scaleEffect(phase == .exit ? 1.3 : 1)
                }
                .ignoresSafeArea()
                .opacity(phase == .exit ? 0 : 1)
                .allowsHitTesting(false)
                .accessibilityHidden(true)
                .task { await play() }
            }
        }
    }

    @MainActor
    private func play() async {
        if reduceMotion {
            await step(.exit, .easeOut(duration: 0.25), hold: 250)
        } else {
            // A beat on the launch frame, so the motion reads as the sun's, not a glitch.
            try? await Task.sleep(for: .milliseconds(120))
            await step(.dip, .spring(duration: 0.3, bounce: 0), hold: 260)
            // The rise is the one place with overshoot: the sun comes up with momentum.
            await step(.rise, .spring(duration: 0.55, bounce: 0.3), hold: 420)
            await step(.exit, .spring(duration: 0.34, bounce: 0), hold: 300)
        }
        finished = true
        onFinish()
    }

    @MainActor
    private func step(_ next: Phase, _ animation: Animation, hold milliseconds: Int) async {
        withAnimation(animation) { phase = next }
        try? await Task.sleep(for: .milliseconds(milliseconds))
    }
}

extension View {
    /// Covers the view with the launch frame, then animates it away once.
    func launchSplash(onFinish: @escaping () -> Void = {}) -> some View {
        modifier(LaunchSplash(onFinish: onFinish))
    }
}
